app:
    resource: @AppBundle/Controller/
    type:     annotation	

presentation:
    resource: "@PresentationBundle/Resources/config/routing.yml"
    prefix:   /platform

login:
    pattern:   /login
    defaults:  { _controller: UserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout